version: '3'
services:
  backend:
    build: ./api
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
  frontend:
    build: ./client
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development

